import { InventoryItem, Category, Supplier, PurchaseOrder, StockMovement } from '@/types';

export const mockCategories: Category[] = [
  {
    id: '1',
    name: 'Electronics',
    description: 'Electronic devices and accessories',
    tenantId: '1',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '2',
    name: 'Clothing',
    description: 'Apparel and fashion items',
    tenantId: '1',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '3',
    name: 'Books',
    description: 'Books and educational materials',
    tenantId: '1',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '4',
    name: 'Home & Garden',
    description: 'Home improvement and gardening supplies',
    tenantId: '1',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
];

export const mockSuppliers: Supplier[] = [
  {
    id: '1',
    name: 'TechCorp Solutions',
    email: 'contact@techcorp.com',
    phone: '+1 (555) 123-4567',
    address: '123 Tech Street, Silicon Valley, CA 94043',
    tenantId: '1',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '2',
    name: 'Fashion Forward Inc',
    email: 'orders@fashionforward.com',
    phone: '+1 (555) 234-5678',
    address: '456 Fashion Ave, New York, NY 10001',
    tenantId: '1',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '3',
    name: 'BookWorld Publishers',
    email: 'sales@bookworld.com',
    phone: '+1 (555) 345-6789',
    address: '789 Literature Lane, Boston, MA 02101',
    tenantId: '1',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
];

export const mockInventoryItems: InventoryItem[] = [
  {
    id: '1',
    name: 'MacBook Pro 16" M3',
    description: 'Apple MacBook Pro 16-inch with M3 chip, 16GB RAM, 512GB SSD',
    sku: 'MBP-16-M3-512',
    categoryId: '1',
    supplierId: '1',
    quantity: 25,
    minQuantity: 5,
    maxQuantity: 50,
    unitPrice: 2499.00,
    costPrice: 2199.00,
    images: ['https://images.pexels.com/photos/18105/pexels-photo.jpg'],
    status: 'active',
    tenantId: '1',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-20'),
    category: mockCategories[0],
    supplier: mockSuppliers[0],
  },
  {
    id: '2',
    name: 'Wireless Bluetooth Headphones',
    description: 'Premium wireless headphones with noise cancellation',
    sku: 'WBH-NC-2024',
    categoryId: '1',
    supplierId: '1',
    quantity: 3,
    minQuantity: 10,
    maxQuantity: 100,
    unitPrice: 299.99,
    costPrice: 199.99,
    images: ['https://images.pexels.com/photos/3394650/pexels-photo-3394650.jpeg'],
    status: 'active',
    tenantId: '1',
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-18'),
    category: mockCategories[0],
    supplier: mockSuppliers[0],
  },
  {
    id: '3',
    name: 'Designer Jeans',
    description: 'Premium denim jeans in various sizes',
    sku: 'DJ-PREM-001',
    categoryId: '2',
    supplierId: '2',
    quantity: 45,
    minQuantity: 20,
    maxQuantity: 100,
    unitPrice: 89.99,
    costPrice: 45.00,
    images: ['https://images.pexels.com/photos/1598507/pexels-photo-1598507.jpeg'],
    status: 'active',
    tenantId: '1',
    createdAt: new Date('2024-01-12'),
    updatedAt: new Date('2024-01-19'),
    category: mockCategories[1],
    supplier: mockSuppliers[1],
  },
  {
    id: '4',
    name: 'Programming Guide: React',
    description: 'Complete guide to React development',
    sku: 'BOOK-REACT-2024',
    categoryId: '3',
    supplierId: '3',
    quantity: 0,
    minQuantity: 15,
    maxQuantity: 75,
    unitPrice: 49.99,
    costPrice: 25.00,
    images: ['https://images.pexels.com/photos/159711/books-bookstore-book-reading-159711.jpeg'],
    status: 'active',
    tenantId: '1',
    createdAt: new Date('2024-01-08'),
    updatedAt: new Date('2024-01-22'),
    category: mockCategories[2],
    supplier: mockSuppliers[2],
  },
  {
    id: '5',
    name: 'Garden Tool Set',
    description: 'Complete set of essential gardening tools',
    sku: 'GTS-COMPLETE-01',
    categoryId: '4',
    supplierId: '1',
    quantity: 18,
    minQuantity: 8,
    maxQuantity: 40,
    unitPrice: 129.99,
    costPrice: 75.00,
    images: ['https://images.pexels.com/photos/4503735/pexels-photo-4503735.jpeg'],
    status: 'active',
    tenantId: '1',
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-01-16'),
    category: mockCategories[3],
    supplier: mockSuppliers[0],
  },
];